config/routes.rb
Rails.application.routes.draw do
  resources :user_sports_masters
  resources :ground_sports_masters
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        sessions: 'users/sessions'
      }
  resources :reservations, only: [:new, :create, :edit, :update]
  resources :grounds, only: [:show, :update, :create, :new, :edit, :destroy]
  resources :users, only: [:show, :update, :create, :new, :edit]
  root 'pages#home'
  get 'groundprofile' => 'grounds#groundprofile'
  get 'about' => 'pages#about'
  get 'groundresults' => 'pages#groundresults'
  get 'reservation_history' => 'pages#reservation_history'
  get 'favorites_list' => 'pages#favorites_list'
  get 'my_grounds' => 'pages#my_grounds'
  post 'ground_search' => 'pages#ground_search' 
  post 'check_in_client' => 'pages#check_in_client'
  post 'add_favorites' => 'pages#add_2_favorites'
  post 'cancelreservation' => 'pages#cancelreservation'
  delete 'destroyall' => 'reservations#destroyall'
  delete 'remove_favorites' => 'pages#remove_from_favorites'
  # user profile
  # reservation history
  # profile edit
end

app/models/ground.rb
class Ground < ApplicationRecord
	belongs_to :user 
	has_many :reservations, dependent: :destroy
	has_many :ground_sports_masters, dependent: :destroy
	has_many :sports_masters, through: :ground_activities
	has_many :user_sports_masters
end

app/controllers/grounds_controller.rb
require 'date'
class GroundsController < ApplicationController
  before_action :set_ground, only: %i[ show edit update destroy ]

  # GET /grounds or /grounds.json
  def index
    @grounds = Ground.all
  end

  def get_all_available_activities_objects
    all_activities = []
    all_activity_objects = SportsMaster.all
    all_activity_objects.each do |activity_obj|
      all_activities.append(activity_obj)
    end
    return all_activities
  end

  def get_all_available_activities
    all_activities = []
    all_activity_objects = SportsMaster.all
    all_activity_objects.each do |activity_obj|
      all_activities.append(activity_obj.name)
    end
    return all_activities
  end

  # GET /grounds/1 or /grounds/1.json
  def show
    @allsportsmasters = get_all_available_activities_objects()
    # GET ACTIVITIES AVAILABLE AT GROUND
    @current_ground_id = params[:id]
    @current_ground_activities = []
    GroundSportsMaster.where(ground_id: @current_ground_id).find_each do |ground_sports_masters_object|
      activity_id = ground_sports_masters_object[:sports_master_id]
      @current_ground_activities.append(SportsMaster.find(activity_id).name)
    end 

    # GET DATES AVAILABLE
    days_for_reservation = 2
    max_number_of_hours_in_a_slot = 2

    # we only want slots of 1 hours but the indexing will start from 0
    # 0th index is ignored because it cannot be used for addition of an hour in "time"
    # so thats why its 2.times

    @current_ground_available_dates = []
    todays_date = Date.today
    days_for_reservation.times do |days_from_today|
      newdate = todays_date + days_from_today
      @current_ground_available_dates.append(newdate.strftime("%d/%m/%Y"))
    end

    # GET AVAILABLE TIME SLOTS
    @available_time_slots = []
    @available_time_slots_4_2weeks = {}
    # hours
    opening_hour = @ground.opening_time.hour
    closing_hour = @ground.closing_time.hour

    opening_time = Time.parse("#{opening_hour}:00 #{todays_date} ")
    closing_time = Time.parse(" #{closing_hour}:00 #{todays_date}")
    @open_time = opening_time.strftime("%I:%M %p")
    @close_time = closing_time.strftime("%I:%M %p")


    slot_starting_hour = opening_hour
    today_date = Date.today
    days_for_reservation.times do |day|

      dropdown_display_date = today_date.strftime("%d %B %Y on %A")
      #appending the display date inside the dropdown
      @available_time_slots.append(dropdown_display_date)

      # while slot starting hour is less than the closing hour
      while slot_starting_hour < closing_hour

        
        max_number_of_hours_in_a_slot.times do |hour|
          slot_finishing_hour = slot_starting_hour + hour

          #ignoring the 0 index
          if hour == 0
            next
          end

          # if finishing hour is less than or equial to closing hour we are good
          if slot_finishing_hour <= closing_hour and slot_finishing_hour <= slot_starting_hour + 1
            @available_time_slots.append("#{slot_starting_hour}:00 = #{slot_finishing_hour}:00 = (#{hour} HOUR)")
          end
        end
        slot_starting_hour = slot_starting_hour + 1
      end
      slot_starting_hour = opening_hour
      today_date = today_date + 1
    end

    # @available_time_slots holds all the time slots that can be available for 2 days
    # @current_ground_booked_slots_hash holds all the time slots that are booked in key value format {activity_name: [slots]}
    # @current_ground_available_slots_hash holds all the time slots that CAN be booked in a key value format {activity_name: [slots]}

    # DATE FILTRATION

    @current_ground_booked_slots_hash = {}
    # @allsportsmasters = SportsMaster.all
    @allsportsmasters.each do |sportsmaster_object|
      #collect all of the reservations which are made for current ground
      reservations = Reservation.where(ground_id: @current_ground_id, sports_master_id:sportsmaster_object.id)
      slots_4_current_activity = []

      # collect all the reservations for current ground which are not inactive in a hash where keys are activity names and values are arrays of available time slots for available time slots
      reservations.each do |reservation_for_current_ground|
        if reservation_for_current_ground.status != INACTIVE_STATUS
          slots_4_current_activity.append("#{Time.at(reservation_for_current_ground.starting_time)} = #{Time.at(reservation_for_current_ground.finishing_time)}")
        end
      end
      @current_ground_booked_slots_hash[sportsmaster_object.name] = slots_4_current_activity
    end

    @current_ground_available_slots_hash = {}
    # @allsportsmasters = SportsMaster.all
    @allsportsmasters.each do |sportsmaster_object|
      @current_ground_available_slots_hash[sportsmaster_object.name] = []      
    end

    # @allsportsmasters = SportsMaster.all
    @allsportsmasters.each do |sportsmaster_object|
      # day is a variable used to index available dates out of an array it starts with -1 
      # because the very first value in a drop down is going to be a date which increments day
      # and since indexes start with 0 the variable is initialized as -1 to later start as 0
      # when its increments in the very first loop

      day = -1
      @available_time_slots.each do |slot|
        if(slot.include?"on")
            @current_ground_available_slots_hash[sportsmaster_object.name].append(slot)
            day = day + 1
            next
        end
        processed_start_time, processed_finish_time = slot.split("=")
        processed_start_time = Time.parse("#{processed_start_time} #{@current_ground_available_dates[day]}")
        processed_finish_time = Time.parse("#{processed_finish_time} #{@current_ground_available_dates[day]}")
        @current_ground_available_slots_hash[sportsmaster_object.name].append("#{processed_start_time} = #{processed_finish_time}")
      end
    end

    # Delete all the available slots that match with booked slots
    @allsportsmasters.each do |sportsactivity|
      @current_ground_booked_slots_hash[sportsactivity.name].each do |booked_slot|
        @current_ground_available_slots_hash[sportsactivity.name].each do |available_slot|
          if available_slot == booked_slot
            @current_ground_available_slots_hash[sportsactivity.name].delete(booked_slot)
          end
        end
      end
    end

    # formatting the filtered out slots for display purpose
    @display_avail_times = []
    @ground_available_reservations = {}
    # ----------------------------------------------------------

    # initializing an empty hash for formatted values for UI display
    @allsportsmasters.each do |sportsmaster_object|
      @ground_available_reservations[sportsmaster_object.name] = []
    end

    @allsportsmasters.each do |asm|
      @current_ground_available_slots_hash[asm.name].each do |available_slot|
        if available_slot.include?"on"
          @ground_available_reservations[asm.name].append(available_slot)
          next
        end
        start, finish = available_slot.split("=")
        start = Time.parse(start).hour
        finish = Time.parse(finish).hour
        @ground_available_reservations[asm.name].append("#{start}:00 to #{finish}:00")
      end
    end

    # CHECK IF CURRENT USER IS OWNER OF THIS GROUND
    if @ground.user_id == current_user.id
      @user_owns_this_ground = true
    else
      @user_owns_this_ground = false
    end

    # CHECK IF CURRENT USER HAS THIS GROUND IN HIS/HER FAVORITES LIST
    user_sports_master_for_ground = UserSportsMaster.where(ground_id: @ground.id, user_id: current_user.id)
    if user_sports_master_for_ground.length > 0
      @favorite = true
    else
      @favorite = false
    end
  end

  # GET /grounds/new
  def new
    @ground = Ground.new
    @all_activities = get_all_available_activities()
  end

  # GET /grounds/1/edit
  def edit
    @sus_user = false
    @current_ground_obj = Ground.find(params[:id])
    if !current_user.ground_owner
      @sus_user = true
    elsif current_user.id != @current_ground_obj.user_id
      @sus_user = true
    end
    ground_sports_master = GroundSportsMaster.where(ground_id: @ground.id)
    @available_activities = []
    ground_sports_master.each do |ground_sports_master_object|
      activity_name = SportsMaster.find(ground_sports_master_object.sports_master_id).name
      @available_activities.append(activity_name)
    end
    @all_activities = get_all_available_activities()
  end

  # POST /grounds or /grounds.json
  def create
    @ground = Ground.new(ground_params)

    #manually saving values that are delivered in array format or need some formating before being inserted
    @ground.opening_time = Time.parse("#{@ground.opening_time.hour}:00")
    @ground.closing_time = Time.parse("#{@ground.closing_time.hour}:00")
    @ground_owner = User.find(ground_params[:user_id])
    @ground_owner.ground_owner = true
    @ground_owner.save
    @ground.save
    activities = params[:ground][:sports_activities]
    if activities 
      activities.each do |activity|
        @sports_master = SportsMaster.where(name:activity)[0]
        @groundsportsmaster = GroundSportsMaster.new()
        @groundsportsmaster.ground_id = @ground.id
        @groundsportsmaster.sports_master_id = @sports_master[:id]
        # if GroundSportsMaster.where(ground_id: @ground.id, sports_master_id: @sports_master.id).length == 0
          @groundsportsmaster.save    
        # end
      end
    end

    respond_to do |format|
      if @ground.save
        format.html { redirect_to @ground, notice: "Ground was successfully created." }
        format.json { render :show, status: :created, location: @ground }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ground.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grounds/1 or /grounds/1.json
  def update
    activities = params[:ground][:sports_activities]

app/helpers/grounds_helper.rb
module GroundsHelper
end

app/views/grounds/_form.html.erb
<div class="new-ground-holder">
  <%= form_with(model: ground) do |form| %>
    <% if ground.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(ground.errors.count, "error") %> prohibited this ground from being saved:</h2>
        <ul>
          <% ground.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% if @ground.ground_name %>
      <div class="custom-jumbotron">
        <div class="container">
          <h1 class=" main-title"><%= @ground.ground_name %></h1>
          <p class="lead-title">Profile Edit</p>
        </div>
      </div>
    <% end %>
    <div class="new-ground-textboxes-holder"> 
      <div class="textboxes-holder col-lg-3 col-sm-12">
        <div class="container justify-center">
          <div class="tb-holder-title">Primary Info</div>
          <div class="new-ground-textbox-holder">
            <div class="new-ground-tb-lables">Ground Name</div>
            <%= form.text_field :ground_name, class: "new-ground-profile-textbox" %>
          </div>

          <div class="new-ground-textbox-holder">
            <div class="new-ground-tb-lables">
              Ground Pincode
            </div>
            <%= form.number_field :ground_pincode, class: "new-ground-profile-textbox pincode-field",min:100000, max:999999, ondrop:"return false;", onpaste:"return false;", onkeypress:"return event.charCode>=48 && event.charCode<=57" %>
          </div>

          <div class="new-ground-textbox-holder">
            <div class="new-ground-tb-lables">
              Location
            </div>
            <%= form.text_area :location, class: "new-ground-profile-textbox" %>
          </div>

          <div class="new-ground-textbox-holder">
            <div class="new-ground-tb-lables">
              Cost Per Hour
            </div>
            <div class="currency-div">
              <span class="currency-symbol-holder">₹</span>
              <%= form.number_field :cost_per_hour, class: "new-ground-profile-textbox", min:0, max:1000, step:10, ondrop:"return false;", onpaste:"return false;", onkeypress:"return event.charCode>=48 && event.charCode<=57"%>
            </div>
          </div>

          

          <div class="new-ground-textbox-holder">
            <div class="new-ground-tb-lables">
              Opening Time
            </div>
            <%= form.time_select :opening_time, {:default => {:hour => '06', :minute => '00'}} %>
          </div>

          <div class="new-ground-textbox-holder">
            <div class="new-ground-tb-lables">
              Closing Time
            </div>
            <%= form.time_select :closing_time, {:default => {:hour => '20', :minute => '00'}} %>
          </div>  
          <p class="w-200" style="margin:auto">Note: please only select hours and not minutes.</p>
            <%= form.hidden_field :user_id, {value:current_user.id}%> 
        </div>
      </div> 
      <div class="textboxes-holder col-lg-3 col-sm-12">
        <div class="container justify-center">
          <div class="tb-holder-title">Contact Info</div>
          <div class="new-ground-textbox-holder">
            <div class="new-ground-tb-lables">
              Business Email
            </div>
              <%= form.email_field :business_email, class: "new-ground-profile-textbox", ondrop:"return false;", onpaste:"return false;", onkeypress:"return (event.charCode>=97 && event.charCode<=122) || (event.charCode>=48 && event.charCode<=57) || event.charCode== 64 || event.charCode== 46" %>
          </div>
          <div class="new-ground-textbox-holder">
            <div class="new-ground-tb-lables">
              Business Phone
            </div>
            <%= form.text_field :business_phone, class: "new-ground-profile-textbox", ondrop:"return false;", onpaste:"return false;", onkeypress:"return event.charCode>=48 && event.charCode<=57" %>
          </div>
        </div>
      </div>
      <div class="textboxes-holder col-lg-3 col-sm-12">
        <div class="container justify-center">
          <div class="tb-holder-title">Activities</div>
            <div class="new-ground-interests-holder">
              <% if @all_activities %>
                <% @all_activities.each do |activity| %>
                  <% if @available_activities != nil %>
                    <% if @available_activities.include?activity %>
                      <div class="new-ground-interest-checkbox-holder">
                        <%= form.check_box :sports_activities, {multiple: true, checked: true}, activity, false%>
                        <div class="new-ground-interest-name"><%= activity %></div>
                      </div> 
                    <% else %>
                      <div class="new-ground-interest-checkbox-holder">
                        <%= form.check_box :sports_activities, {multiple: true}, activity, false%>
                        <div class="new-ground-interest-name"><%= activity %></div>
                      </div> 
                    <% end %>
                  <% else %>
                    <div class="new-ground-interest-checkbox-holder">
                      <%= form.check_box :sports_activities, {multiple: true}, activity, false%>
                      <div class="new-ground-interest-name"><%= activity %></div>
                    </div> 
                  <% end %>
                <% end %>
              <% end %>
            </div>  
        </div>
      </div>
    </div>
    <div class="submit-div">
      <%= form.submit "SAVE", class: "btn-success btn submit-btn"%>
    </div>
  <% end %>  
</div>

app/views/grounds/edit.html.erb
<div class="ground-creation-background">
  <% if @sus_user %>
  <% controller.redirect_to root_path, notice:"Unauthorized access" %>
  <%else%>
  <%= render 'pages/header'%>

  <%= render 'form', ground: @ground %>

  <% end %>  
</div>

app/views/grounds/groundprofile.html.erb
<div class="ground-profile-holder">
	<%= render 'pages/header'%>
	<div class="ground-profile">
		<div class="ground-profile-title-holder">
			<h3 class="home-reservation-title">GROUND</h3>
		</div>
		<div class="ground-profile-main">
			<div class="ground-profile-name">
				GROUNDNAME
			</div>
			<hr>
			<div class="ground-profile-location">
				<div class="smaller-title">Location:</div>
				<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium</p>
			</div>
			<hr>
			<div class="ground-profile-contact">
				<div class="smaller-title">Contact:</div>
				<span>Email:</span><p>business@email.com</p>
				<span>Phone:</span><p>8989898989</p>
			</div>
			<hr>
			<div class="ground-profile-activities">
				<div class="smaller-title">Activities:</div>
				<div class="user-activities-holder">
					<div class="ground-profile-interests">
						<% ['activity', 'activity1', 'activity2', 'activity3'].each do |activity| %>
							<div class="ground-activity"><%= activity %></div>
						<% end %>
					</div>
				</div>
			</div>
			<hr>
			<div class="ground-profile-cph">
				<div class="smaller-title">Cost/Hour:</div><span>$$</span>
			</div>
			<hr>
			<div class="ground-profile-reservation-form-holder">
				<div class="smaller-title">Reservation:</div>
				<%= form_with url: new_reservation_path, method: :post do |form| %>
					<div>
						<%= form.select(:selected_activity,['Cricket', 'Football', 'Basketball', 'Volleyball'], {:prompt => "Activity"}, {:class => "selected_activity" }) %>
						<%= form.select(:date, @current_ground_available_dates, {:prompt => "Date"}, {:class => "selected_activity" }) %>
						<%= form.select(:time_slot,['slot1', 'slot2', 'slot3'], {:prompt => "Time Slot"}, {:class => "selected_activity" }) %>	
					</div>
					<div class="submit-div">
						<%= form.submit "SUBMIT", class:"btn btn-success"%>
					</div>
				<% end %>
			</div>
			<hr>
			<div class="ground-profile-options">
				<div class="option-div">
					<%= button_tag "Options", onclick:"document.getElementById('mymodal').style.display='block'", class:"submit-button", class: "option-button" %>
				</div>
				<% if user_signed_in? %>
					<% if current_user.ground_owner %>
						<div id="mymodal" class="modal">
						    <div class="my-modal-content animate-top">
						      	<header class="w3-container w3-teal"> 
							        <span onclick="document.getElementById('mymodal').style.display='none'" 
							        class="w3-button w3-display-topright close-modal">&times;</span>
							        <div class="options-title">OPTIONS</div>
						      	</header>
						      	<hr>
						      	<div class="options-list">
							    	<p class="options-list-a"><%= link_to "All Reservations", "link", class: "options-list-a" %></p>
							    	<p class="options-list-a"><%= link_to "Ground Profile Edit", edit_ground_path(id:1), class: "options-list-a" %></p>
							    	<p class="options-list-a"><%= link_to "Reservation Settings", "/ruby-book", class: "options-list-a" %></p>
							    	<p class="options-list-a"><%= link_to "About", "/ruby-book", class: "options-list-a" %></p>
						      	</div>
						    </div>
						</div>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/grounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grounds</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Ground name</th>
      <th>User</th>
      <th>Ground pincode</th>
      <th>Business email</th>
      <th>Business phone</th>
      <th>Cost per hour</th>
      <th>Opening time</th>
      <th>Closing time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grounds.each do |ground| %>
      <tr>
        <td><%= ground.id %></td>
        <td><%= ground.ground_name %></td>
        <td><%= ground.user_id %></td>
        <td><%= ground.ground_pincode %></td>
        <td><%= ground.business_email %></td>
        <td><%= ground.business_phone %></td>
        <td><%= ground.cost_per_hour %></td>
        <td><%= ground.opening_time %></td>
        <td><%= ground.closing_time %></td>
        <td><%= link_to 'Show', ground %></td>
        <td><%= link_to 'Edit', edit_ground_path(ground) %></td>
        <td><%= link_to 'Destroy', ground, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ground', new_ground_path %>

app/views/grounds/new.html.erb
<div class="ground-creation-background">
  <%= render 'pages/header'%>


<div class="new-ground-body">
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class=" main-title">CREATE A NEW GROUND</h1>
      <p class="lead-title">Create your own ground's profile by inserting required details</p>
    </div>
  </div>
  <%= render 'form', ground: @ground %>
</div>

<%= link_to 'Back', grounds_path %>
  
</div>

app/views/grounds/show.html.erb
<div class="ground-profile-background">
  <%= render 'pages/header'%>
  <div class="gp-holder">
    <% if notice %>
      <div class="welcome-note-container">
        <div class="home-welcome-note">
          <%= notice %>
        </div>
        <div class="pointer">
        </div>
      </div>
    <% elsif alert %>
      <div class="welcome-note-container">
        <span class="home-welcome-note">
          <%= alert %>
        </span>
        <div class="pointer">
        </div>
      </div>
    <% end %>
    <div class="gp-main"> 
      <div class="custom-jumbotron gp-jumbotron">
        <div class="container gp-container">
          <div>
            <h1 class="main-title"><%= @ground.ground_name %></h1>
            <p class="lead-title">Ground Profile</p>  
          </div>
          <div class="jumbotron-btn-div">
            <% if @favorite %>
              <%= link_to "Remove Favorite", remove_favorites_path(ground_id: @current_ground_id), method: :delete, class:"btn btn-secondary cancel-btn jumbotron-btn"%>
            <% else %>
              <%= link_to "Add to Favorites", add_favorites_path(ground_id: @current_ground_id), method: :post, class:"btn btn-success cancel-btn jumbotron-btn"%>
            <% end %>
            <% if @user_owns_this_ground %>
                <%= button_tag "Options", onclick:"document.getElementById('mymodal').style.display='block'", class:"btn btn-success jumbotron-btn"%>
            <% end %>
          </div>
        </div>
      </div>
      <div class="new-ground-textboxes-holder">
        <div class="show-ground-textboxes-holder col-lg-4 col-sm-12">
          <div class="container justify-center">
            <div class="tb-holder-title" >Primary Info</div>

            <% if @ground.location %>
              <div class="gp-textbox-holder w-200">
                <div class="gp-smaller-title">Ground Location:</div>
                <div class="gp-location"><%= @ground.location %></div>
              </div>
            <% end %>

            <div class="gp-textbox-holder w-200">
              <div class="gp-smaller-title">Opening Time:</div>
              <div><%= @open_time %></div>
            </div>

            <div class="gp-textbox-holder w-200">
              <div class="gp-smaller-title">Closing Time:</div>
              <div><%= @close_time %></div>
            </div>

            <div class="gp-textbox-holder w-200">
              <div class="gp-smaller-title">Cost Per Hour:</div>
              <div><%= @ground.cost_per_hour %></div>
            </div>
          </div>
          
        </div>
        <!-- ---------------------------------------- -->
        <div class="col-lg-4 col-sm-12">  
          <div class="show-ground-textboxes-holder col-lg-12  contact-info-tb-holder">
            <div class="container justify-center">
              <div class="tb-holder-title">Contact Info</div>
                <% if @ground.business_email %>
                  <div class="gp-textbox-holder w-200">
                    <div class="gp-smaller-title">Email:</div>
                    <div><%= @ground.business_email %></div>
                  </div>
                <% end %>
                <% if @ground.business_phone > 0 %>
                  <div class="gp-textbox-holder w-200">
                    <div class="gp-smaller-title">Phone:</div>
                    <div><%= @ground.business_phone %></div>
                  </div>
                <% end %>
            </div>
          </div>
          <div class="show-ground-textboxes-holder col-lg-12 reservation-tb-holder ">
            <div class="container justify-center">
              <div class="tb-holder-title">Reserve</div>
                <div class="gp-textbox-holder">
                  <%= form_with url: reservations_path, method: :post do |form| %>
                    <div class="res-form-holder">
                      <%= form.select(:selected_activity, @current_ground_activities, {:prompt => "Activity"}, {:id => "activity-select"}, ) %>

                      <% today = @current_ground_available_dates %>

                      <% @allsportsmasters.each do |asm| %>
                        <div id="<%= asm.name %>" class="hidden-selects" style="display: none;">
                          <select name="date_time" prompt="date-time" class="date-time-select">
                            <% day = -1 %>
                            <option value="" selected="selected" disabled><%=asm.name%> Date & Time</option>
                            <% @ground_available_reservations[asm.name].each do |date|%>
                              <% if date.include?"on" %>
                                <option value='<%= date %>' disabled><%= date %></option>
                                <% day = day + 1 %>
                              <% else %>
                                <%= value = today[day].to_s + " = " + date.to_s%>
                                <option value="<%= value %>"><%= date %></option>
                              <% end %>
                            <% end %>
                          </select>  
                        </div>
                        
                      <% end %>
                      <%= form.hidden_field :user_id, {value:current_user.id}%>
                      <%= form.hidden_field :ground_id, {value:@current_ground_id}%>
                      <%= form.hidden_field :cost, {value:@ground.cost_per_hour}%>
                  </div>
                  <div class="submit-div">
                      <%= form.submit "BOOK", class:"btn btn-success"%>
                  </div>
                  <% end %>
                </div>
            </div>
          </div>
        </div>
        <!-- ------------------------------------------------- -->
        <div class="show-ground-textboxes-holder col-lg-4 col-sm-12">
          <div class="container justify-center">
            <div class="tb-holder-title">Available Acitvities</div>
            <div class="gp-textbox-holder gp-tb-holder">
              <!-- <div class="gp-smaller-title">Activities:</div> -->
                  <div class="gp-interests">
                    <% @current_ground_activities.each do |activity| %>
                      <div class="activity"><%= activity %></div>
                    <% end %>
                  </div>
            </div>  
          </div>
        </div>
        <!-- ---------------------------------------------------- -->
      </div>
        <div id="mymodal" class="modal">
          <div class="my-modal-content animate-top">
            <header class="w3-container w3-teal"> 
              <span onclick="document.getElementById('mymodal').style.display='none'" 
              class="w3-button w3-display-topright close-modal">&times;</span>
              <div class="options-title">OPTIONS</div>
            </header>
            <div class="options-list">
              <div class="modal-option-holder">
                <%= link_to "All Reservations", reservation_history_path("history_for": "ground",ground_id: @current_ground_id), class: "options-list-a" %>
              </div>
              <div class="modal-option-holder">
                <%= link_to "Ground Profile Edit", edit_ground_path(id: @current_ground_id), class: "options-list-a" %>
              </div>              
              <div class="modal-option-holder">
                <%= link_to "About", about_path, class: "options-list-a" %>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>

</div>

<script type="text/javascript">
  document.getElementById('activity-select').addEventListener('change', function() {
    // invdiv = document.getElementById('invisible-div').innerHTML
    // document.getElementById('dates-4-activity').innerHTML = invdiv

    allHiddenDivs =document.querySelectorAll(".hidden-selects");
    for (let i = 0; i < 8; i++){
      document.querySelectorAll(".hidden-selects")[i].style.display = "none"
    }
    document.getElementById(this.value).style.display = "block"
    });
</script>