config/routes.rb
Rails.application.routes.draw do
  resources :user_sports_masters
  resources :ground_sports_masters
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        sessions: 'users/sessions'
      }
  resources :reservations, only: [:new, :create, :edit, :update]
  resources :grounds, only: [:show, :update, :create, :new, :edit, :destroy]
  resources :users, only: [:show, :update, :create, :new, :edit]
  root 'pages#home'
  get 'groundprofile' => 'grounds#groundprofile'
  get 'about' => 'pages#about'
  get 'groundresults' => 'pages#groundresults'
  get 'reservation_history' => 'pages#reservation_history'
  get 'favorites_list' => 'pages#favorites_list'
  get 'my_grounds' => 'pages#my_grounds'
  post 'ground_search' => 'pages#ground_search' 
  post 'check_in_client' => 'pages#check_in_client'
  post 'add_favorites' => 'pages#add_2_favorites'
  post 'cancelreservation' => 'pages#cancelreservation'
  delete 'destroyall' => 'reservations#destroyall'
  delete 'remove_favorites' => 'pages#remove_from_favorites'
  # user profile
  # reservation history
  # profile edit
end

app/views/pages/_guestnave.html.erb
<nav class="home-navbar" style="display: flex; justify-content: space-between;">
	<div id ="" class="cancel-btn" style="width:50%; font-size: 20px; margin-left:20px">GroundCheck</div>
	<div class="">
	    <%= link_to "About",
	    about_path,	class: "nav-link cancel-btn" %>
	</div>
</nav>

app/views/pages/_header.html.erb
<nav class="home-navbar">
	<div id ="logo" class="logo" onclick="document.getElementById('mySidebar').style.width = '250px'">&#9776; GroundCheck</div>
	<div id ="logo" class="shortlogo"  onclick="document.getElementById('mySidebar').style.width = '250px'">
		&#9776; GC
	</div>

	<div class="nav-stuff">
		<%= form_with url: "/groundresults", method: :get, class:"search-form" do |form| %>
		  <%= form.text_field :search_word, placeholder: "search grounds", ondrop:"return false;", onpaste:"return false;", onkeypress:"return (event.charCode>=97 && event.charCode<=122) || (event.charCode>=48 && event.charCode<=57) || (event.charCode>=65 && event.charCode<=90) || event.charCode == 32", class: "search-bar form-control mr-sm-2" %>
		  <%= form.submit "Search", class: "btn btn-success search-button cancel-btn" %>
		<% end %>
	</div>
	<div class="favorite-btn-div">
		<a href="/favorites_list">
			<%= image_tag "star.png", height: "20px" %>
		</a>
	</div>
</nav>
<div id="mySidebar" class="sidebar">
	<div>
		<button  class="btn btn-danger close-sidebar-button" onclick="document.getElementById('mySidebar').style.width = '0'">&times;</button>
		<!-- //HERE -->
		<div class="sidebar-userprofile">
			<%= link_to current_user.name, current_user %>
			<!-- <a href=""><%= current_user.name %></a> -->
		</div>
		<%= link_to "Home", root_path %>
		<%= link_to "Reservation History", reservation_history_path("history_for": "user") %>
		<% if !current_user.ground_owner %>
			<%= link_to "Create Your Ground", new_ground_path %>
		<% end %>
		<!-- <span><%= link_to "My Grounds", my_grounds_path %></span> -->
		
		<%= link_to "Edit Your Profile", edit_user_path(current_user.id) %>
		<%= link_to "About", about_path %>
	</div>
	<div class="signout-btn-div">
		<!-- <button class="btn signout-btn btn-outline-danger"><a href=""></a>Sign Out</button>		 -->
		<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn signout-btn btn-danger"%>
	</div>
</div>

app/views/pages/about.html.erb
<div class="home-container">
	<div class="home-body" style="display: flex; flex-direction:column; align-items: center; justify-content:center; height:100%">
		<div class="custom-jumbotron" >
			<div class="container">
				<h1 class="main-title">ABOUT</h1>
				<p class="lead-title" style="line-height: 1.5;">GroundCheck is an app that makes booking a playground for specific time more efficient. 
				Its a web page that allows you to check at what time the play ground is abailable and figure 
				out which time slots to book using a simple user friendly UI. Reservation and cost per hour 
				will be displayed in the information section of the playground.</p>
			</div>
		</div>
		<%= link_to "Home", root_path, class:"btn btn-light" %>	
	</div>
</div>

app/views/pages/favorites_list.html.erb
<div class="favorite-list-background">
	<%= render 'pages/header'%>
	<div class="favorites-list-body">
			<div class="custom-jumbotron w-100">
			  <div class="container">
			    <h1 class=" main-title">Favorites List</h1>
			    <p class="lead-title">This is a list of all the grounds you like.</p>
			  </div>
			</div>
			<div class="favorite-grounds-holder">
				<% if @favorite_grounds != []%>
					<% @favorite_grounds.each do |fav_ground| %>
					<div class="col-lg-4 col-sm-12" style="padding:5px">
						<div class="favorite-ground-post" style="color:white;">
							<div class="ground-result-post-title">
								<% ground_name = fav_ground.ground_name %>
								<span><%= ground_name[0..15] %></span>
							</div>
							<% if fav_ground.location %>
								<div>
									<div class="ground-result-post-subtitle">Location:</div>
									<% ground_location = fav_ground.location%>
									<div><%= ground_location[0..50] %></div>
								</div>
							<% end %>
							<div class="favorite-ground-post-btn-holder">
								<%= link_to 'VISIT', fav_ground, class: "btn btn-success cancel-btn"%>
							</div>
						</div>
					</div>
					<% end %>
				<% elsif @favorite_grounds == [] %>
					<h3>YOU HAVE NO FAVORITE GROUNDS SELECTED</h3>
				<% end %>
			</div>		
	</div>
	
</div>

app/views/pages/groundresults.html.erb
<div class="ground-result-background">
	<%= render 'pages/header'%>
	<div class="groundresults-body">
		
		<div class="ground-results-viewer">
			<div class="custom-jumbotron w-100">
			  <div class="container">
			  	<% searchword = @searchword %>
			    <h1 class=" main-title">
			    	Search result for "<%= searchword[0..15] %>"
			    </h1>
			    <p class="lead-title"><%= @results.length %> grounds matched to your search</p>
			  </div>
			</div>
			<div class="ground-results-holder">
				<% @results.each do |ground| %>
					<div class="col-lg-4 col-sm-12" style="padding:5px">
						<div class="ground-result-post">
							<div class="ground-result-post-title">
								<% ground_name = ground.ground_name %>
								<span><%= ground_name[0..15] %></span>
							</div>
							<% if ground.location %>
								<div>
									<div class="ground-result-post-subtitle">Location:</div>
									<% ground_location = ground.location%>
									<div><%= ground_location[0..40] %></div>
								</div>
							<% end %>
							<div>
								<%= link_to 'VISIT', ground, class: "btn btn-success cancel-btn"%>
							</div>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
	<div class= "home-container" id="home">
	<% if user_signed_in? %>
	<%= render 'pages/header'%>
		<div class="home-body">
		<div class="welcome-note-container">
			<span class="home-welcome-note">
				Welcome <%= current_user.name %>
			</span>
		</div>
		<% if notice %>
			<div class="welcome-note-container">
				<div class="home-welcome-note">
					<%= notice %>
				</div>
				<div class="pointer">
				</div>
			</div>
		<% elsif alert %>
			<div class="welcome-note-container">
				<span class="home-welcome-note">
					<%= alert %>
				</span>
				<div class="pointer">
				</div>
			</div>
		<% end %>
		<div class="custom-jumbotron">
		  <div class="container">
		    <h1 class=" main-title">GROUNDCHECK</h1>
		    <p class="lead-title">Welcome <%= current_user.name %>, make reservations and stay at the top of your game.</p>
		  </div>
		</div>
			<div class="reservations-viewer custom-jumbotron">
				<div class="container">
					<h2 class="secondary-title">RESERVATIONS</h2>
					<div class="reservations-holder">
					<% if @current_user_reservations %>
						<% @current_user_reservations.each do |reservation| %>
							<div class="col-lg-3 col-sm-12" style="padding-right:2px; padding-left: 2px;">
								<% case reservation[:status] %>
									<% when @active %>
										<div class="home-reservation-post want-tooltip" title="<%=reservation[:obj].status.upcase %>" style="background:#56776C">
									<% when @hour_left %>
										<div class="home-reservation-post want-tooltip" title="<%=reservation[:obj].status.upcase %>" style="background:#22577A">
									<% when @play_on %>
										<div class="home-reservation-post want-tooltip" title="<%=reservation[:obj].status.upcase %>" style="background:#F55C47">
									<% when @checked_in %>
										<div class="home-reservation-post want-tooltip" title="<%=reservation[:obj].status.upcase %>" style="background:#50D890">
								<% end %>
									<div class="home-reservation-post-info-holder">
										<div class="home-reservation-ground-name">
											<% if reservation[:ground_name].length > 13 %>
												<%= reservation[:ground_name][0..12]+".." %>
											<%else%>
												<%= reservation[:ground_name]%>
											<%end%>
										</div>
										<div class="home-reservation-date">
											<%= reservation[:reserved_activity] %>
										</div>
										<div class="home-reservation-post-datetime-holder">
											<div class="home-reservation-date"><%= reservation[:reservation_date] %></div> 
											<div class="home-reservation-time"><%= reservation[:startingtime] %></div>	
										</div>	
									</div>
									<div>
										<%= link_to image_tag("delete.png",height: "25px", color:"orange"), cancelreservation_path(id: reservation[:obj].id), method: :post, class: "want-tooltip cancel-btn res-cancel-btn", data: { confirm: 'Are you sure?' }, "title":"CANCEL" %>
									</div>
								</div>
							</div>
						<% end %>
					<% end %>
					<% if @current_user_reservations != nil and @current_user_reservations.length == 0 %>
						<p class="no-reservation-notice">
							WOW, CURRENTLY YOU HAVE NO RESERVATIONS
						</p>
						<!-- <div class="submit-div">
							<%= link_to "SHOW GROUNDS", groundresults_path, class: "btn btn-success cancel-btn" %>
						</div> -->
					<% end %>
					</div>
				</div>
			</div>
			<% if current_user.ground_owner %>
				<div class="reservations-viewer custom-jumbotron">
					<div class="container">
						<h2 class="secondary-title">GROUND ADMINISTRATION</h2>
						<div class="admin-reservations-holder">
							<% if @owned_ground_reservations %>
								<% @owned_ground_reservations.each do |reservation| %>
									<div class="col-lg-4 col-sm-12">
										<div class="home-ground-admin-post">
											<div class="home-reservation-post-info-holder">
												<div class="home-admin-user-name">
													<% if reservation[:username].length > 15 %>
														<%= reservation[:username][0..14]+".." %>
													<%else%>
														<%= reservation[:username]%>
													<%end%>
												</div>
												<div class="home-admin-reservation-activity">
													<%= reservation[:reserved_activity] %>
													<%= reservation[:obj].status %>
												</div>
												<div class="home-reservation-post-datetime-holder">
													<div class="home-reservation-date"><%= reservation[:reservation_date] %></div> 
													<div class="home-reservation-time"><%= reservation[:startingtime] %></div>	
												</div>	
												<div class="home-admin-reservation-btn-holder">
													<% if reservation[:obj].status != "checked_in" %>
														<%= link_to "Check In", check_in_client_path(id: reservation[:obj].id), method: :post, class: "check-in-btn cancel-btn" ,data: { confirm: 'Are you sure?' } %>
													<% else %>
														<%= link_to "Checked In", check_in_client_path(id: reservation[:obj].id), method: :post, class: "checked-in-btn", disabled:true ,data: { confirm: 'Are you sure?' } %>
													<% end %>
												</div>
											</div>
										</div>
									</div>
								<% end %>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>
				
			<div class="user-interest-holder custom-jumbotron">
				<div class="container">
					<h3 class="secondary-title">YOUR INTERESTS</h3>

					<div class="home-user-interests">
						<% if @current_user_reservations %>
							<% @current_user_interests.each do |interest| %> 
								<div class="activity"><span><%= interest %></span></div>
							<% end %> 
						<% end %>
					</div>
				</div>
			</div>
		<% else %>
			<div class="home-guest-main-div background-front-image">
				<%= render 'pages/guestnave'%>
				<div class="home-guest-body ">
					<% if notice %>
						<div class="welcome-note-container">
							<div class="home-welcome-note">
								<%= notice %>
							</div>
							<div class="pointer">
							</div>
						</div>
					<% elsif alert %>
						<div class="welcome-note-container">
							<span class="home-welcome-note">
								<%= alert %>
							</span>
							<div class="pointer">
							</div>
						</div>
					<% end %>
					<div class="custom-jumbotron " style="height:100%; background:transparent; color:white">
					  <div class="container">
					    <h1 class=" main-title">GROUNDCHECK</h1>
					    <p class="lead-title">
					    	Welcome to GroundCheck, please sign up or sign in to use our services
					    </p>
					    <p>
					    	<div class="home-btn-holder">
									<%= link_to "Sign In", new_user_session_path, class:" cancel-btn sign-in-btn"%>
									<%= link_to "Sign Up",  new_user_registration_path, class:"cancel-btn sign-up-btn"%>
								</div>	
					    </p>
					  </div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
  	$('[data-toggle="tooltip"]').tooltip(); 
	});
</script>

app/views/pages/reservation_history.html.erb
<% if @sus_user%>
	<% controller.redirect_to root_path, notice: "Unauthorized access!" %>
<% else %>
<div class="reservation-history-background">
	<%= render 'pages/header'%>
	<div class="reservations-history-body" >
		<div class="custom-jumbotron w-100">
		  <div class="container">
		    <h1 class=" main-title">RESERVATIONS HISTORY</h1>
		    <p class="lead-title">Record of all the reservations you have made.</p>
		  </div>
		</div>
		<% if @active_reservations_history != [] or @active_reservations_history == nil %>
			<div class="custom-jumbotron w-100">
				<div class="container">
					<h3 class="secondary-title center">ACTIVE RESERVATIONS</h3>
				</div>
			</div>
			<div class="reservations-history-holder">
				<% if @active_reservations_history %>
					<% @active_reservations_history.each do |resservation_history_hash| %>
						<div class="col-lg-4 col-sm-12" style="padding:5px">
							<div class="reservations-history-post" style="color:white;">
								<div class="reservations-history-post-info-holder">
									<% if resservation_history_hash[:history_for] == "ground"%>
										<div class="reservations-history-ground-name">
											<%= resservation_history_hash[:username]%>
										</div>
									<% else %>
										<div class="reservations-history-ground-name">
											<%= resservation_history_hash[:ground_name]%>
										</div>
									<% end %>
									<div class="reservations-history-post-datetime-holder">
										<div class="reservations-history-date">
											<span class="reservations-history-small-title">Date:</span><%= resservation_history_hash[:reservation_date] %>
										</div> 

										<div class="reservations-history-time">
											<span class="reservations-history-small-title">Starts At:</span><%= resservation_history_hash[:startingtime] %>
										</div>	

										<div class="reservations-history-time">
											<span class="reservations-history-small-title">Created On:</span><%= resservation_history_hash[:created_at] %>
										</div>	

										<div class="reservations-history-time">
											<span class="reservations-history-small-title">Cost:</span>₹<%= resservation_history_hash[:cost] %>
										</div>	
									</div>	
									<div class="submit-div">
										<%= link_to 'VISIT GROUND', resservation_history_hash[:ground_obj], class: "btn btn-success cancel-btn reservations-history-res-btn" %>
									</div>
								</div>
							</div>
						</div>
					<% end %>
				<% end %>
			</div>
		<% end %>
		<% if @inactive_reservations_history != [] or @inactive_reservations_history == nil %>
			<div class="custom-jumbotron w-100">
				<div class="container">
					<h3 class="secondary-title center" >INACTIVE RESERVATIONS</h3>
				</div>
			</div>
			<div class="reservations-history-holder">
				<% if @inactive_reservations_history %>
					<% @inactive_reservations_history.each do |resservation_history_hash| %>
						<div class="col-lg-4 col-sm-12" style="padding:5px">
							<div class="reservations-history-post" style="color:white;">
								<div class="reservations-history-post-info-holder">
									<% if resservation_history_hash[:history_for] == "ground"%>
										<div class="reservations-history-ground-name" >
											<%= resservation_history_hash[:username]%>
										</div>
									<% else %>
										<div class="reservations-history-ground-name" >
											<%= resservation_history_hash[:ground_name]%>
										</div>
									<% end %>
									<div class="reservations-history-post-datetime-holder">
										<div class="reservations-history-date"><span class="reservations-history-small-title">Date:</span><%= resservation_history_hash[:reservation_date] %></div> 

										<div class="reservations-history-time"><span class="reservations-history-small-title">Starts At:</span><%= resservation_history_hash[:startingtime] %></div>	

										<div class="reservations-history-time"><span class="reservations-history-small-title">Created On:</span><%= resservation_history_hash[:created_at] %></div>

										<div class="reservations-history-time">
											<span class="reservations-history-small-title">Cost:</span>₹<%= resservation_history_hash[:cost] %>
										</div>


										<!-- <div class="reservations-history-time"><span class="reservations-history-small-title">Cost:</span><%= resservation_history_hash[:created_at] %></div>	 -->
									</div>	
									<div class="submit-div">
										<%= link_to 'VISIT GROUND', resservation_history_hash[:ground_obj], class: "btn btn-success cancel-btn reservations-history-res-btn" %>
									</div>
								</div>
							</div>
						</div>
					<% end %>
				<% end %>
			</div>	
		<% end %>	
	</div>
</div>

<% end %>