config/routes.rb
Rails.application.routes.draw do
  resources :user_sports_masters
  resources :ground_sports_masters
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        sessions: 'users/sessions'
      }
  resources :reservations, only: [:new, :create, :edit, :update]
  resources :grounds, only: [:show, :update, :create, :new, :edit, :destroy]
  resources :users, only: [:show, :update, :create, :new, :edit]
  root 'pages#home'
  get 'groundprofile' => 'grounds#groundprofile'
  get 'about' => 'pages#about'
  get 'groundresults' => 'pages#groundresults'
  get 'reservation_history' => 'pages#reservation_history'
  get 'favorites_list' => 'pages#favorites_list'
  get 'my_grounds' => 'pages#my_grounds'
  post 'ground_search' => 'pages#ground_search' 
  post 'check_in_client' => 'pages#check_in_client'
  post 'add_favorites' => 'pages#add_2_favorites'
  post 'cancelreservation' => 'pages#cancelreservation'
  delete 'destroyall' => 'reservations#destroyall'
  delete 'remove_favorites' => 'pages#remove_from_favorites'
  # user profile
  # reservation history
  # profile edit
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :user
	belongs_to :ground
	belongs_to :sports_master
end

app/controllers/reservations_controller.rb
require 'date'
require 'time'
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    # PARSING AND CONFIGURING FOR SUITABLE STORAGE FORMAT
    # DATE
    received_date, received_time = params[:date_time].split("=")
    received_time = received_time.split("-")[0]

    # TIME
    processed_date = Date.parse(received_date)
    processed_start_time, processed_finish_time = received_time.split("to")
    processed_start_time = Time.parse("#{processed_start_time} #{processed_date}").to_i
    processed_finish_time = Time.parse("#{processed_finish_time} #{processed_date}").to_i
        
    # USER
    res_user_id = params[:user_id]

    # GROUND
    res_ground_id = params[:ground_id]

    # ACTIVITY
    sports_master_record = SportsMaster.where(name: params[:selected_activity])[0]
    reservation_sports_master_id = sports_master_record.id
    reservation_cost = params[:cost]

    # COLLECTING ALL CONFIGURED PARAMS
    reservation_info = {:date => processed_date, :user_id => res_user_id, :ground_id => res_ground_id, :sports_master_id => reservation_sports_master_id, :starting_time => processed_start_time, :finishing_time => processed_finish_time, :cost => reservation_cost}
    @ground = Ground.find(res_ground_id)
    @reservation = Reservation.new(reservation_info)    
    respond_to do |format|
      if @reservation.save
        format.html { redirect_to root_path, notice: "Reservation was successfully created. Refresh to see latest updates on your reservations." }
      else
        format.html { redirect_to root_path, notice: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:date, :user_id, :ground_id, :sports_master_id, :starting_time, :finishing_time, :cost)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :ground_id %>
    <%= form.number_field :ground_id %>
  </div>

  <div class="field">
    <%= form.label :sports_master_id %>
    <%= form.number_field :sports_master_id %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :starting_time %>
    <%= form.time_select :starting_time %>
  </div>

  <div class="field">
    <%= form.label :finishing_time %>
    <%= form.time_select :finishing_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Active</th>
      <th>User</th>
      <th>Ground</th>
      <th>Selected activity</th>
      <th>Starting time</th>
      <th>Finishing time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.active %></td>
        <td><%= reservation.user_id %></td>
        <td><%= reservation.ground_id %></td>
        <td><%= reservation.sports_master_id %></td>
        <td><%= reservation.starting_time %></td>
        <td><%= reservation.finishing_time %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Destroy All', destroyall_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @reservation.user_id %>
</p>

<p>
  <strong>Ground:</strong>
  <%= @reservation.ground_id %>
</p>

<p>
  <strong>Selected activity:</strong>
  <%= @reservation.sports_master_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @reservation.date %>
</p>

<p>
  <strong>Starting time:</strong>
  <%= @reservation.starting_time %>
</p>

<p>
  <strong>Finishing time:</strong>
  <%= @reservation.finishing_time %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>