config/routes.rb
Rails.application.routes.draw do
  resources :user_sports_masters
  resources :ground_sports_masters
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        sessions: 'users/sessions'
      }
  resources :reservations, only: [:new, :create, :edit, :update]
  resources :grounds, only: [:show, :update, :create, :new, :edit, :destroy]
  resources :users, only: [:show, :update, :create, :new, :edit]
  root 'pages#home'
  get 'groundprofile' => 'grounds#groundprofile'
  get 'about' => 'pages#about'
  get 'groundresults' => 'pages#groundresults'
  get 'reservation_history' => 'pages#reservation_history'
  get 'favorites_list' => 'pages#favorites_list'
  get 'my_grounds' => 'pages#my_grounds'
  post 'ground_search' => 'pages#ground_search' 
  post 'check_in_client' => 'pages#check_in_client'
  post 'add_favorites' => 'pages#add_2_favorites'
  post 'cancelreservation' => 'pages#cancelreservation'
  delete 'destroyall' => 'reservations#destroyall'
  delete 'remove_favorites' => 'pages#remove_from_favorites'
  # user profile
  # reservation history
  # profile edit
end

app/models/ground_sports_master.rb
class GroundSportsMaster < ApplicationRecord
	belongs_to :ground
	belongs_to :sports_master
end

app/controllers/ground_sports_masters_controller.rb
class GroundSportsMastersController < ApplicationController
  before_action :set_ground_sports_master, only: %i[ show edit update destroy ]

  # GET /ground_sports_masters or /ground_sports_masters.json
  def index
    @ground_sports_masters = GroundSportsMaster.all
  end

  # GET /ground_sports_masters/1 or /ground_sports_masters/1.json
  def show
  end

  # GET /ground_sports_masters/new
  def new
    @ground_sports_master = GroundSportsMaster.new
  end

  # GET /ground_sports_masters/1/edit
  def edit
  end

  # POST /ground_sports_masters or /ground_sports_masters.json
  def create
    @ground_sports_master = GroundSportsMaster.new(ground_sports_master_params)

    respond_to do |format|
      if @ground_sports_master.save
        format.html { redirect_to @ground_sports_master, notice: "Ground sports master was successfully created." }
        format.json { render :show, status: :created, location: @ground_sports_master }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ground_sports_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ground_sports_masters/1 or /ground_sports_masters/1.json
  def update
    respond_to do |format|
      if @ground_sports_master.update(ground_sports_master_params)
        format.html { redirect_to @ground_sports_master, notice: "Ground sports master was successfully updated." }
        format.json { render :show, status: :ok, location: @ground_sports_master }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ground_sports_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ground_sports_masters/1 or /ground_sports_masters/1.json
  def destroy
    @ground_sports_master.destroy
    respond_to do |format|
      format.html { redirect_to ground_sports_masters_url, notice: "Ground sports master was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ground_sports_master
      @ground_sports_master = GroundSportsMaster.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ground_sports_master_params
      params.require(:ground_sports_master).permit(:ground_id, :sports_master_id)
    end
end

app/helpers/ground_sports_masters_helper.rb
module GroundSportsMastersHelper
end

app/views/ground_sports_masters/_form.html.erb
<%= form_with(model: ground_sports_master) do |form| %>
  <% if ground_sports_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ground_sports_master.errors.count, "error") %> prohibited this ground_sports_master from being saved:</h2>

      <ul>
        <% ground_sports_master.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ground_id %>
    <%= form.number_field :ground_id %>
  </div>

  <div class="field">
    <%= form.label :sports_master_id %>
    <%= form.number_field :sports_master_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ground_sports_masters/edit.html.erb
<h1>Editing Ground Sports Master</h1>

<%= render 'form', ground_sports_master: @ground_sports_master %>

<%= link_to 'Show', @ground_sports_master %> |
<%= link_to 'Back', ground_sports_masters_path %>

app/views/ground_sports_masters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ground Sports Masters</h1>

<table>
  <thead>
    <tr>
      <th>Ground</th>
      <th>Sports master</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ground_sports_masters.each do |ground_sports_master| %>
      <tr>
        <td><%= ground_sports_master.ground_id %></td>
        <td><%= ground_sports_master.sports_master_id %></td>
        <td><%= link_to 'Show', ground_sports_master %></td>
        <td><%= link_to 'Edit', edit_ground_sports_master_path(ground_sports_master) %></td>
        <td><%= link_to 'Destroy', ground_sports_master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ground Sports Master', new_ground_sports_master_path %>

app/views/ground_sports_masters/new.html.erb
<h1>New Ground Sports Master</h1>

<%= render 'form', ground_sports_master: @ground_sports_master %>

<%= link_to 'Back', ground_sports_masters_path %>

app/views/ground_sports_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ground:</strong>
  <%= @ground_sports_master.ground_id %>
</p>

<p>
  <strong>Sports master:</strong>
  <%= @ground_sports_master.sports_master_id %>
</p>

<%= link_to 'Edit', edit_ground_sports_master_path(@ground_sports_master) %> |
<%= link_to 'Back', ground_sports_masters_path %>